using System;

namespace PracticeProgramming.ProjectEuler
{
    public static class EvenFibonacciNumbers
    {
        public static void SolveProblem()
        {
            // Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
            // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            // Problem: Solved

            const int maxNumber = 4000000;
            var previousNumber = 1;
            var nextNumber = 1;
            var tempNumb = 0;
            var sum = 0;

            while (previousNumber <= maxNumber)
            {
                if (previousNumber % 2 == 0)
                {
                    sum += previousNumber;
                }

                tempNumb = previousNumber;
                previousNumber = nextNumber;
                nextNumber = nextNumber + tempNumb;
            }

            Console.WriteLine(sum);
        }
    }
}
